# Generated by Django 5.2 on 2025-07-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ptusername',
            new_name='username',
        ),
    ]
